Mobile First Project Pull Request
HERMON-1995/My-portfolio pull request #1
Opened 2023-01-12 19:21 UTC by HERMON-1995

Set up and Mobile first project is about building mobile version of the first page using Html and CSS.

2023-01-12 19:54 UTC, mukhammadrizooff requested changes
Hi @HERMON-1995, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 19:54 UTC, mukhammadrizooff commented on index.html
> +        <header class="header">
- [ ] [OPINION] In my opinion it will be nice if you open the `section` tag after the `header` tag 👍🏼

2023-01-12 19:54 UTC, mukhammadrizooff commented on index.html
> +        </header>
- [ ] [REQUIRED] Good job so far! The `logo` (if the design has one) should be on the left and has an `a` link (`a` tag). This is for three reasons: `convention`, `semantics`, and `user` experience(`UX`). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info and the `hamburger` button is on the `right` and has a `nav` tag. The `nav` tag is for the `semantics` reason and the right position for convention and user experience for mobile devices.


```HTML
<header>
    <a href...>Website Logo</a>
    <nav>
        <!-- Main Navigation inside <header> -->
        <ul>
            <li></li>
        </ul>
    </nav>
</header>
```

2023-01-12 19:54 UTC, mukhammadrizooff commented on index.html
> +                <p class="par-1">Hey there. I'm Hermon</p>
- [ ] [REQUIRED] Please change the `p` tag to the 'hx' tag(o.s `h1`) 🙏🏼

2023-01-12 19:54 UTC, mukhammadrizooff commented on index.html
> +                <p class="par-2">I'm a software developer</p>
- [ ] [REQUIRED] Please change the `p` tag to the 'hx' tag(o.s `h2`) 🙏🏼

2023-01-12 19:54 UTC, mukhammadrizooff commented on index.html
> +                </nav>
- [ ] [REQUIRED] Nice work but the list of icons should use a `ul`(❌) tag to group them, and `li`(❌) per icon; each icon has a link (`a` tag ✔️) and remove `nav` tag because `nav` tag should create inside `header` tag for navigation elements. Please implement my suggestions 🙏🏼 ||✔️ => Done; ❌ => Not Implemented

2023-01-13 06:29 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @HERMON-1995  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️professional README👍 
✔️professional PR👍 
✔️No linter errors👍

## Optional requirements ♻️ 
_Check the comments below 👇_

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 06:29 UTC, TuyishimireEric commented on style.css
> +}
- [ ] **[Optional]** I think it would be better to remove a fixed width for your sections 
to make your mobile version responsive until the desktop screen size. 😉😉 

   You may try to use the ```width: 100%``` to make it responsive 😎😎

2023-01-13 06:29 UTC, TuyishimireEric commented on index.html
> +                    <img class="scroll-button" src="/Header-images/Scroll icone.svg" alt="Scroll button">
- [ ] **[Optional]** These icons are not showing, Kindly try to adjust your links to make your icons visible 🙏 

![image](https://user-images.githubusercontent.com/102757126/212249584-3380fcfd-f488-46fe-a4fe-5df17f11ecff.png)

2023-01-13 06:29 UTC, TuyishimireEric commented on style.css
> +}
- [ ]  **[Optional]** I think it would be better to adjust your background image link and try to add a dot to your link  

You may change it to ```background-image: url('./Header-images/backgroundimg.svg');``` 😎😎

![image](https://user-images.githubusercontent.com/102757126/212251397-d44293ae-32c2-47d2-b552-eee015fe6c60.png)

2023-01-13 06:29 UTC, TuyishimireEric commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] **[Optional] Good job on using the MICROVERSE Readme template 👍** However,

    I think it would be better to provide a  valid **LICENSE** link in your **README** as open source software needs to be licensed to provide rights to **modify**, **distribute** other than creator :joy: 

    _we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish._

2023-01-20 04:51 UTC, merged