Popup window Pull request
HERMON-1995/My-portfolio pull request #12
Opened 2023-01-31 19:10 UTC by HERMON-1995

This project is all about building popup page using JavaScript dynamically in JS file. Here is some of my changes:

            > Created elements with JavaScript methods.
            > Created DOM events when clicked.
            > Selected elements using index of arrays.

2023-01-31 19:51 UTC, topeogunleye requested changes
Hi @HERMON-1995, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Nothing to mention

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 19:51 UTC, topeogunleye commented on index.html
>       <nav class="site-nav">
- [ ] As required, please kindly ensure that the mobile menu popup follows the design for both desktop and mobile versions from [the chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) (e.g., font, colours, images, text, margins). 
- Currently the mobile menu for your mobile is also showing on desktop. please fix it to have the same design as your desktop;

| Title  | Image Comparison |
| ------------- | ------------- |
| Your Design  |  <img width="943" alt="image" src="https://user-images.githubusercontent.com/52934128/215861709-66eb8e02-d1a8-4ee9-ab8c-6b58be14bb0d.png"> |
| Figma Design | <img width="587" alt="image" src="https://user-images.githubusercontent.com/52934128/215862138-f74c59dd-98bf-4775-8e23-3ab77191b6cb.png">  |

2023-01-31 19:51 UTC, topeogunleye commented on index.html
> +     <ul class="nav-menu">
- [ ] I kindly suggest that you ensure that your hamburger is responding to click and bringing up a modal. 
- When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- When the user clicks (or taps) the close (X) button, the popup disappears.
- The popup is responsive, it fits mobile and desktop sizes properly.

2023-01-31 19:51 UTC, topeogunleye commented on index.html
>                   <li class="javascript">JavaScript</li>
- [ ] Great job adding your project modals dynamically 👍, however you also need to add your project cards themselves dynamically as you did for the project modal.

- [ ] Kindly implement an array of objects to store your JavaScript objects containing the information for each project.

## EXAMPLE
```javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```

- [ ] I kindly suggest that you ensure the Modal popup data is populated with the data from the projects array.

2023-01-31 19:51 UTC, topeogunleye commented on index.html
>       <nav class="site-nav">
- [ ] I kindly suggest that you fix your mobile menu display on desktop as you currently have two menus displayed on desktop with one causing a giant horizontal scroll that makes the user not have a good experience browsing the website. please kindly fix it. I explain more in the video below:

https://www.loom.com/share/e8e9aca30c8243a8b73a610d9a6a61bf

2023-02-01 10:18 UTC, m05e5 approved these changes
**Hi @HERMON-1995 

You did great. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Descriptive PR 
✔️ your linters are all ok

## Optional suggestions


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**

2023-02-01 11:53 UTC, merged