Desktop version project Pull request
HERMON-1995/My-portfolio pull request #5
Opened 2023-01-19 18:24 UTC by HERMON-1995

This project is about building desktop version of the last project mobile first version.

2023-01-19 18:46 UTC, Owusu-Desmond requested changes
Hi @HERMON-1995 and @valt19  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: :red_circle: 

You have submitted a project, that does not have a descriptive pull request description so please make sure that your pull Request has a short summary describing the introduced changes in more detail.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-19 20:27 UTC, Zuhaib042 requested changes
Hi @HERMON-1995 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![so close](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
✅ Linters passing
✅ Correct Github flow

## Required Changes ♻️

- [ ] I noticed that you are not merging the feature branches in `main` after getting approved from code reviewers. Kindly consider merging the feature branch into `main` after getting approved, and then for the new milestone, you can create another feature branch from `main`. that way your new feature branch would have the latest changes. and the next code reviewer will only see the new changes introduced in new feature branch.
kindly have a look at Github flow in this [link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/git_github_basics.md)
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] The commit messages should be written in the imperative tense and should be meaningful and the first letter should also be capitalized. Ex: "Add images to the project" instead of "adding images". [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 20:27 UTC, Zuhaib042 commented on style.css
> +}
- [ ] Good work using the grid for layout. but these lines are messing up the whole design because all the sections in your page are taking the twelve-column layout approach which is not working right and all the sections in bigger displays are not centered properly. Kindly consider centering your headings and cards as in the Figma design.
- [ ] I would suggest fixing the same problem in the `About me` section as well for the same reasons.
your design
![kjh](https://user-images.githubusercontent.com/96683843/213548280-99131efe-9f0f-4b39-9c1b-5e3fcde11b4b.jpg)

figma design

![vb](https://user-images.githubusercontent.com/96683843/213548632-e1543464-1f15-4878-aa25-4888bb047ec6.jpg)

2023-01-19 20:27 UTC, Zuhaib042 commented on index.html
> +           </ul>
- [ ] These social media icons' images are not showing up. I can see that the link in the src attribute is not correct. kindly consider not giving empty spaces in your images names in Header-images folder and then by giving relative link here will make them work just fine.
- [ ] kindly consider placing these icons in the footer (which would be the last element on your page) and adding a `grey top border` on the footer to make it similar to the figma design.

2023-01-19 20:27 UTC, Zuhaib042 commented on index.html
> +           <div class="email-container"><p class="email-address">hermonghiwot1995@gmail.com</p></div>
- [ ] This email is not needed in the desktop version. kindly consider removing it making it similar to the Figma design.

2023-01-19 20:27 UTC, Zuhaib042 commented on index.html
> +        </section>
- [ ] Good job adding the form but I think fixing some small issues will make it great looking just like in the figma design. kindly consider fixing these following:
- [ ] The text on the left should have `30px` font-size like in the figma design.
- [ ] Kindly consider giving some top and bottom margin to this section to make it similar to the figma design.
- [ ] The `get in touch` button should be left aligned as in the figma design.
your design
![lk](https://user-images.githubusercontent.com/96683843/213552493-461652fe-e100-46d6-94c1-d17dfb27ee44.jpg)


figma design
![lkj](https://user-images.githubusercontent.com/96683843/213552460-9ed53f13-ccc7-41de-af66-57741a6f7f9a.jpg)

2023-01-20 11:23 UTC, levy002 approved these changes
## Hello @HERMON-1995 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Highlights
- Descriptive PR description :heavy_check_mark: 
- Professional README :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 13:20 UTC, merged